### PR TITLE
chore(dep) Upgrade dependencies for Cicero 0.20.10

### PR DESCRIPTION
**Pull request by jeromesimeon**
Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

This upgrades dependencies for:
- latest markdown transform `0.10.4`
- upcoming Cicero `0.20.19`
- corresponding version of the markdown editor for upcoming Cicero `0.20.10`

### CODE REVIEW

**Comment by jeromesimeon** [comment]
> I might be missing something, but why not do proper releases of markdown-editor and cicero-core before upgrading?

Done!

**Comment by irmerk** [comment]
Should this be pointing to the release from `markdown-editor` that comes from the Slate47 branch we are going to make?

**Comment by DianaLease** [comment]
> Should this be pointing to the release from `markdown-editor` that comes from the Slate47 branch we are going to make?

I don't think we need a new release after we make the branch.

**Comment by jeromesimeon** [comment]
> Should this be pointing to the release from `markdown-editor` that comes from the Slate47 branch we are going to make?

I don't think so. If we do that we cannot do the automated release (which only works on master). I think the plan is to save that trouble and do the release first, then create the `slate47` branch to reflect the release.

As far as I know we are not planning to do a release of the markdown editor from the `slate47` branch (unless we really have to). Markdown editor has already been release anyway.

Note: this is a comment which is independent from this PR. This PR only updates the dependencies.

**Pull request merged**
