### PR TITLE
feat(*): add storybook for developer focused demo - I315

### PR DESCRIPTION
**Pull request by sanyamdogra**
# Issue #315 
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
- Adds `@storybook/react` as a dependency.
- Access Storybook at port 9001 by running `npm run storybook`.
- Component stories can be added in `src/stories` folder with extension `.stories.js`

### Flags
- N.A

### Related Issues
- Issue #315 

### Screenshots
image
image

### CODE REVIEW

**Comment by irmerk** [comment]
This is done with @elit-altum as far as I understand.

**Comment by jeromesimeon** [comment]
> This is done with @elit-altum as far as I understand.

Can you clarify this? Who wrote the code, and who signed the DCO?

**Comment by irmerk** [comment]
@jeromesimeon see the work in #335

**Comment by irmerk** [comment]
@sanyamdogra can you check to ensure these changes are still in `master`?

**Comment by sanyamdogra** [comment]
Hi @irmerk, Yes they have been added to the `master`.

**Pull request merged**
