### PR TITLE
feat(Security Vulnerability): removed yarn.lock

### PR DESCRIPTION
**Pull request by Innovator007**
Signed-off-by: Iliyas Attarwala [iliyasattarwala007@gmail.com](iliyasattarwala007@gmail.com)
# Issue #99 

### Changes
- Removed yarn.lock file from the project dependencies tracking making package-lock.json as the main file.
- Run tests to ensure everything works fine.

### CODE REVIEW

**Comment by Innovator007** [comment]
Hi @mttrbrts thanks for reviewing the PR but isn't the issue in difficulty medium ?

**Comment by Innovator007** [comment]
And we can close the Issue #99 since its resolved now right?

**Comment by mttrbrts** [comment]
Closed #99, sorry, this is a starter difficulty IMO. Thanks for your help!

**Comment by Innovator007** [comment]
Okay thanks @mttrbrts

**Comment by irmerk** [comment]
@Innovator007 I may have misjudged the work involved on the difficulty level, but you're getting the AP+Hacktoberfest shirt already so no worries :stuck_out_tongue_winking_eye:

**Comment by Innovator007** [comment]
Hey @irmerk no problem on the difficulty level i understand and thanks for the great news :)

**Pull request merged**
