### PR TITLE
feat(components) add header tooltip - I120

### PR DESCRIPTION
**Pull request by johnnyqbui**
# Issue #120 
hovering over clause template header title will pop up a tooltip if header has been truncated.

### Changes
- use named imports instead of default from `actions` to utilize `titleGenerator` function to display title on tooltip.
- create state for hover effect.
- tooltip pops up with full title if header is truncated (> 54 characters in length) and hovered over.
- Images following, hovering when header title is not truncated:
Screen Shot 2019-10-06 at 12 14 08 AM

- hovering when header title is truncated:

Screen Shot 2019-10-06 at 11 13 54 AM

### Flags
- 

### Related Issues
- Issue #121 
- Issue #120

### CODE REVIEW

**Comment by irmerk** [comment]
I'm not able to reproduce this with your branch. I'm not getting the tooltip nor the truncation being in effect. @DianaLease are you able to? The code looks solid, I may be having version issues on my local machine. 

Screen Shot 2019-10-06 at 12 25 22 PM

**Comment by DianaLease** [comment]
This works great for me both in the cicero-ui demo and when linked with TSv2.

TSv2:
Screen Shot 2019-10-07 at 2 15 12 PM

cicero-ui:
Screen Shot 2019-10-07 at 2 09 09 PM

Nice job!

**Comment by irmerk** [comment]
Super cool @johnnyqbui! @Michael-Grover note that this was just merged in.

**Comment by Michael-Grover** [comment]
@johnnyqbui very nice, thank you!

**Pull request merged**
