### PR TITLE
feat(plugin,contractEditor): add keyboard shortcuts - #215

### PR DESCRIPTION
**Pull request by 98lenvi**
Signed-off-by: lenvi <lenvin@oykuapp.com>

# Issue #215 
Add Keyboard shortcut support via Plugin.

### Changes
- I have added a Plugin "KeyPlugin.js" which will allow for keyboard shortcuts and it depends upon the toolbarMethods present in @accordproject/markdown-editor
  - Appended the plugins array in ContractEditor
  - Created a plugin file 
  - Shortcut Added ar as follows
        1. Ctrl+b: bold
        2. Ctrl+i: italics
        3. Ctrl+Alt+c: code
        4. Ctrl+q: quote
        5. Ctrl+Shift+7: ordered list
        6. Ctrl+Shift+8: unordered list

### Flags
- I want this to be reviewed and get feedback on my approach. Since the keyboard shortcut for 'quotes' isn't the standard one, I hope we can discuss about which keyboard shortcut will lead to what action. i.e. I need some guidance
- I have not added shortcut key for 'Link"

### Related Issues
- Issue #215

### CODE REVIEW

**Comment by irmerk** [comment]
An initial thought is that this may be better suited for `markdown-editor`, thoughts @dselman?

**Comment by irmerk** [comment]
@Michael-Grover any thoughts on a shortcut for a link or if we should have one?

**Comment by irmerk** [comment]
I think this approach is a great start! @98lenvi what about `CMD` for Mac? I think `CMD+B` on Mac is typically similar to `CTRL+B`, but with this code `CMD+B` doesn't work.

**Comment by DianaLease** [comment]
> An initial thought is that this may be better suited for `markdown-editor`, thoughts @dselman?

I would agree with that

**Comment by irmerk** [comment]
> An initial thought is that this may be better suited for `markdown-editor`, thoughts @dselman?

@98lenvi that just means transfer the code into `markdown-editor`, mostly to the existing [`onKeyDown` ](https://github.com/accordproject/markdown-editor/blob/master/src/SlateAsInputEditor/index.js#L339). And we can transfer the issue to `markdown-editor`.

**Comment by Michael-Grover** [comment]
> @Michael-Grover any thoughts on a shortcut for a link or if we should have one?

Usually the shortcut for a link is cmd K, I use it often so I think other users will expect that shortcut as well

**Comment by irmerk** [comment]
Yeah so I think start a new PR after implementing this same-ish code in `markdown-editor`, and we can go from there on more feedback @98lenvi

**Comment by dselman** [comment]
Couple of things I noticed:
1. Bold and italic seem to behave differently (Safari). When you press CTRL-B it toggles bold but maintains the selection. When you press CTRL-I it toggles italic but the selection is lost and the cursor position is before the previous selection

2. Is the `CTRL-&` and `CTRL-*` obvious to people? It feels like a newline starting with a `*` or a `1.` would be a more natural way to create a new `ul` or `ol`

**Comment by Michael-Grover** [comment]
Be sure to check what Microsoft Word and Google Docs do since that is the software our users will be most familiar with

**Comment by 98lenvi** [comment]
Should I open an issue in `markdown-editor`? When I was implementing the fix even I thought it would be better to do the changes in `markdown-editor`.

`CTRL-&` and `CTRL-*` is being used in Slack and Google Docs, so I used it.

Thank you very much for the feedback

**Comment by irmerk** [comment]
@98lenvi I transferred the original issue to `markdown-editor` [here](https://github.com/accordproject/markdown-editor/issues/244)

**Comment by irmerk** [comment]
Closing this, move work to `markdown-editor`

**Pull request closed without merging**
