### PR TITLE
refactor(src): Font Size Change From px To em - I58

### PR DESCRIPTION
**Pull request by florenciasilva**
Signed-off-by: florenciasilva <hensgrej@gmail.com>

# Issue #58 
Change in font-size to help with responsiveness.

### Changes
- Change of all font-size from px to em.

### Flags
- Found 1 high severity vulnerability after npm install.   

### Related Issues
- Issue [#43](https://github.com/accordproject/template-studio-v2/issues/43)
- Pull Request [#89](https://github.com/accordproject/template-studio-v2/pull/89)

### CODE REVIEW

**Comment by irmerk** [comment]
@florenciasilva

I think you could run `npm audit` to see if that fixes the `1 high severity vulnerability`.

Also, were you able to test this in Template-Studio-v2? You can do it with `npm link`, which I can provide some help on if you haven't used before.

**Comment by florenciasilva** [comment]
> @florenciasilva
> 
> I think you could run `npm audit` to see if that fixes the `1 high severity vulnerability`.
> 
> Also, were you able to test this in Template-Studio-v2? You can do it with `npm link`, which I can provide some help on if you haven't used before.

I'm testing it right now to see if anything is looking not right, and yeah the npm audir fix fixed the high severity, i'm gonna include it in a second commit!

**Comment by florenciasilva** [comment]
It should all look good now! There is a 2px difference in the `content` class, but apparently it comes from another source and since it also is `em`, it changed slightly. But apart from that, everything else is like the production version as far as I can tell!

**Comment by irmerk** [comment]
> It should all look good now! There is a 2px difference in the `content` class, but apparently it comes from another source and since it also is `em`, it changed slightly. But apart from that, everything else is like the production version as far as I can tell!

This looks good to me, @DianaLease are you aware of there being any issue with not having an original size for the `em`s to inherit?

**Comment by DianaLease** [comment]
> > It should all look good now! There is a 2px difference in the `content` class, but apparently it comes from another source and since it also is `em`, it changed slightly. But apart from that, everything else is like the production version as far as I can tell!
> 
> This looks good to me, @DianaLease are you aware of there being any issue with not having an original size for the `em`s to inherit?

No issue. If there is nothing to inherit, by default, 1em will be the equivalent of 16px (this is based on the browser default, which is basically always 16px).

**Pull request merged**
