### PR TITLE
fix(TemplateLibrary): Button styling

### PR DESCRIPTION
**Pull request by abnazhor**
# Issue #184 
Added style to button inside TemplateLibrary.

### Changes
- Added styles for hover and default style for "New Clause Template" Button.

### CODE REVIEW

**Comment by Michael-Grover** [comment]
What's the best way to see a preview of this button?

**Comment by Michael-Grover** [comment]
@irmerk showed me how, thanks

**Comment by abnazhor** [comment]
Okay, I'll fix it. Thanks!

**Comment by abnazhor** [comment]
Hello, I've found out that the icon has the exact same colour, but it doesn't have 100% opacity (.8 opacity instead), that's because it seems to have a different colour, what should I do?
imagen

**Comment by irmerk** [comment]
I believe the icon is coming from here (https://github.com/accordproject/cicero-ui/blob/master/src/TemplateLibrary/TemplateActions.js#L53) and should have a color style applied to overwrite the current style?

**Comment by abnazhor** [comment]
The thing is, now it has the correct color, what happens is that its opacity is not 100%, that's why its colour looks weird.

**Comment by irmerk** [comment]
> The thing is, now it has the correct color, what happens is that its opacity is not 100%, that's why its colour looks weird. Is it okay to override that property?

Ah I see. It should be fine, yes.

**Comment by Michael-Grover** [comment]
Why are the opacities different in the first place? Is it a semantic UI thing?

**Comment by abnazhor** [comment]
It's probably a semantic UI thing, looking at its class ".ui.button". I've been researching what to do but I'm not sure what fix to apply as everything I can think of doesn't look that good.

**Comment by abnazhor** [comment]
I've come with a fix that is using an specific selector to remove it. What do you think of it? If it's okay, where should I put it?
`button.ui.button i {
    opacity: 1 !important;
}`

**Comment by DianaLease** [comment]
> I've come with a fix that is using an specific selector to remove it. What do you think of it? If it's okay, where should I put it?
> `button.ui.button i { opacity: 1 !important; }`

should be able to put it in `src/styles.css`

**Comment by abnazhor** [comment]
Oh! I put it correctly then, thank you!

**Comment by Michael-Grover** [comment]
@abnazhor looks great, thank you!

**Pull request merged**
