### PR TITLE
docs(VariablePlugin): init docs - I146

### PR DESCRIPTION
**Pull request by Innovator007**
Signed-off-by: Iliyas Attarwala [iliyasattarwala007@gmail.com](iliyasattarwala007@gmail.com)
# Issue #146 

### Changes
- Added documentation of VariablePlugin for developers.

### CODE REVIEW

**Comment by Innovator007** [comment]
Hi @irmerk , i have changed the things you requested for and yes i have the latest version of master and that yarn.lock file is showing up because i merged the latest code from master of this repo to my repository and thats why its showing up here, otherwise you can merge this code to master and it won't affect anything.

**Comment by Innovator007** [comment]
Hi @irmerk can you review the changes you requested and close this. Thanks :)

**Comment by irmerk** [comment]
@Innovator007 yes, waiting on others' review as well.

**Comment by Innovator007** [comment]
Hi @irmerk , @mttrbrts are there any changes needed more?

**Pull request merged**
