### PR TITLE
docs(README): plugins updates

### PR DESCRIPTION
**Pull request by starblind**
Signed-off-by: Kedar Thakur <453473+starblind@users.noreply.github.com>

# Issue #<NUMBER HERE>
misc README fixes

### Changes
* use syntax highlighting
* add some notes about `ClausePlugin`
* add missing links

### Flags
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>

### Related Issues
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>

### CODE REVIEW

**Comment by starblind** [comment]
@irmerk - is this what you were thinking?

**Comment by irmerk** [comment]
Indeed! I think just rebase and we can merge this.

**Comment by starblind** [comment]
updated the branch

**Comment by irmerk** [comment]
Also email admin@accordproject.org for swag

**Pull request merged**
