### PR TITLE
Misspelling across the repo

### PR DESCRIPTION
**Pull request by kanav-raina**
Signed-off-by: kanav-raina <kanavraina98@gmail.com>
Corrected library spelling in UI Components > CiceroUI

# Issue #294 
Wrong spelling of library in CiceroUI

### Changes
library spelling corrected in UI Components > CiceroUI

### Related Issues
- Issue #<294>

### CODE REVIEW

**Comment by mttrbrts** [comment]
Good find @kanav-raina , can you pick the DCO sign off, please? https://github.com/accordproject/cicero-ui/pull/317/checks?check_run_id=477883779

**Comment by mttrbrts** [comment]
Also, please see the contributing guidelines, to make your commit messages follow our convention.

**Comment by kanav-raina** [comment]
I have removed the DCO sign off.

**Comment by irmerk** [comment]
@kanav-raina addressing this in https://github.com/accordproject/markdown-editor/issues/251

**Pull request closed without merging**
