### PR TITLE
fix(*): add netlify.toml to show storybook build in netlify - #356

### PR DESCRIPTION
**Pull request by 98lenvi**
Signed-off-by: lenvi <lenvin@oykuapp.com>

# Issue #356 
Added `netlify.toml` to initialize a Netlify build for the Storybook demo

### Changes
- Created a new configuration file `netlify.toml` 
  - for production, that is the demo build. Storybook will be build
  - for pull/merge request previews, the pervious demo build will be used.
  -  added nothing for the development environment.
  - added a redirect rule, regardless of any path will be redirected to the main page.
- Now Netlify will show the storybook build.
- [Preview from my fork is available here](https://musing-mclean-8fc189.netlify.com/?path=/story/components-contract-editor--contract-editor)

### Flags
- Netlify should be pointed towards the development branch to see changes. 
- Please let me know if it is breaking anything else (like npm publish)
- I'm not sure about its behavior in pull/merge requests.
- Resources referred:
  - [Netlify's guide on setting up the toml file](https://docs.netlify.com/configure-builds/file-based-configuration/#build-settings )
  - [Common configurations for other apps](https://docs.netlify.com/configure-builds/common-configurations/#javascript-spas)

### Related Issues
- Issue #356

### CODE REVIEW

**Comment by irmerk** [comment]
This is great! A few thoughts, because I think this will need to be put on hold:

> * Now Netlify will show the storybook build.

I think this is what we will want to do once the Storybook build is accomplishing at least what the current demo build does - we want to see changes implemented in the PR. At least that's what I understood, @DianaLease thoughts?

> * Netlify should be pointed towards the development branch to see changes.

We will be switching back to `master` and getting rid of `development` (see recent Slack discussions for this)

**Comment by 98lenvi** [comment]
@irmerk, I agree with you on keeping this on hold until the Storybook build is satisfactory. Do you want the changes in Storybook to be done in this PR? I'd love to work on Storybook(I'm not familiar with it, but I can learn).

> Netlify should be pointed towards the development branch to see changes.
The reason why I mentioned this is because the storybook related commits are in the development branch, the script will work fine with the master branch provided the Storybook related changes are in the master branch.

**Comment by irmerk** [comment]
I believe @sanyamdogra and @elit-altum were working on this, need to check with them on what the status is there.

Unsure about the branches, it's getting too complicated and will be easier to handle when we revert back to `master` and get rid of `development`

**Comment by irmerk** [comment]
Any update on this @98lenvi?

**Comment by 98lenvi** [comment]
@irmerk, It looks like #315 hasn't seen any progress from where it was. Can I continue on that?

**Comment by irmerk** [comment]
Sure thing @98lenvi, comment in #315 and I'll assign it.

**Comment by irmerk** [comment]
@98lenvi this can be closed because #382 is merged, correct?

**Comment by 98lenvi** [comment]
Yes, @irmerk. I'm closing this pull request. Thank you!

**Pull request closed without merging**
