### PR TITLE
test(components): add tests for titleGenerator & headerGenerator - #123

### PR DESCRIPTION
**Pull request by 98lenvi**
Signed-off-by: lenvi <lenvin@oykuapp.com>

# Issue #123 
Added tests for  `titleGenerator` & `headerGenerator`
### Changes
- The changes :
  - Added one more case for `headerGenerator` i.e, the util must not throw an error when `inputTitle` is not passed as props.
  - Added a test for `titleGenerator`, since this util is straight forward, I have added only one test case

### Flags
- A discussion on what more test cases could be added would help me. 

### Related Issues
- Issue #123

### CODE REVIEW

**Comment by irmerk** [comment]
This is a great start. I was thinking more about an integrations test approach, where we mock the activity of a user to make sure changes don't necessarily alter that functionality. So, for instance, if the `ContractEditor` has a clause template in it:
- is the user unable to edit text? 
- Is the user able to edit the variables?
- can the user click on a conditional variable?

Adding this to #123 also.

**Comment by 98lenvi** [comment]
@irmerk Okie! I'll try it out, but it'll take some time because I'm new to writing tests :disappointed: .

**Comment by irmerk** [comment]
Not a problem, this isn't a high priority.

**Comment by irmerk** [comment]
Just rebase with master and I'll merge this in, and you can work off #123 still if you're inclined to do so.

**Comment by 98lenvi** [comment]
@irmerk, I have first pulled the changes from the upstream, merged with my branch, then performed the rebase. Please tell me whether have I followed the correct steps

**Comment by irmerk** [comment]
That's fine for now. In the future when working on a branch within a fork, I'd go with:

```bash
  git checkout master
  git fetch --all --prune
  git rebase upstream/master
  git push origin master
  git checkout 98lenvi-issue123-action-tests
  git rebase master
  git push origin 98lenvi-issue123-action-tests -f
```

**Pull request merged**
