### PR TITLE
 test(components): init testing to clause component - I118

### PR DESCRIPTION
**Pull request by jolanglinais**
# Issue #118
Add testing and documentation for `ClauseComponent`

### Changes
- Implement testing for `ClauseComponent` functionality
- Add heading title documentation for `ClauseComponent`

### Flags
N/A

### Related Issues
- Issue #89 
- PR #121

### CODE REVIEW

**Comment by devcer** [comment]
@irmerk  I would like to work on this. Which component should I pick first?

**Comment by irmerk** [comment]
@devcer I'm not sure I understand. This is a merged PR, there isn't anything to work on, or is there?

**Comment by devcer** [comment]
Oops. Sorry. I thought you wanted someone to write unit tests for the code.

**Comment by irmerk** [comment]
@devcer there are some issues tracking testing in this repo: https://github.com/accordproject/cicero-ui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+test

**Pull request merged**
