### PR TITLE
[WIP]feat(*): developer focused demo using StoryBook - I315

### PR DESCRIPTION
**Pull request by elit-altum**
Signed-off-by: elit-altum <manan.sharma311@gmail.com>

# Issue #315

### Changes
- Currently added ```@storybook/react``` as a dev dependency and ```script``` to start storybook.
- This is currently for staging purpose

### Related Issues
- Issue #315

### CODE REVIEW

**Comment by elit-altum** [comment]
@sanyamdogra I think we can start from here.
Please go through  https://stackoverflow.com/questions/41588025/git-github-push-to-someone-elses-fork-of-my-repo. I think this is a good way to collaborate on a single PR. What do you say?

**Comment by elit-altum** [comment]
@irmerk needed your thoughts on some initial settings 
1. Where should we write and store the stories, as in what directory should we use? Storybook recommends co-locating in the ```src``` folder itself.
2. Is the script to run storybook okay? I used the recommended ```npm run storybook```

**Comment by sanyamdogra** [comment]
> @sanyamdogra I think we can start from here.
> Please go through https://stackoverflow.com/questions/41588025/git-github-push-to-someone-elses-fork-of-my-repo. I think this is a good way to collaborate on a single PR. What do you say?

Well I don't think I'll be comfortable on working on a same PR. It'll lead to discrepancies in future. This might make sense have made sense if we use the same fork.

**Comment by sanyamdogra** [comment]
> @irmerk needed your thoughts on some initial settings
> 
> 1. Where should we write and store the stories, as in what directory should we use? Storybook recommends co-locating in the `src` folder itself.
> 2. Is the script to run storybook okay? I used the recommended `npm run storybook`

1. We will include a . stories.js for every component present in the project.
2. Yes npm run storybook looks good to me.

**Comment by elit-altum** [comment]
> > @sanyamdogra I think we can start from here.
> > Please go through https://stackoverflow.com/questions/41588025/git-github-push-to-someone-elses-fork-of-my-repo. I think this is a good way to collaborate on a single PR. What do you say?
> 
> Well I don't think I'll be comfortable on working on a same PR. It'll lead to discrepancies in future. This might make sense have made sense if we use the same fork.

Unsure of what you asked for. Are you referring to collaborator access to a fork? Yes I will have to provide you that on my fork.

**Comment by irmerk** [comment]
I think working off a fork and building a draft PR from that fork would be best.

Script seems fine. And I would presume to follow what they say in their docs, so colocating sounds fine.

**Comment by sanyamdogra** [comment]
> > > @sanyamdogra I think we can start from here.
> > > Please go through https://stackoverflow.com/questions/41588025/git-github-push-to-someone-elses-fork-of-my-repo. I think this is a good way to collaborate on a single PR. What do you say?
> > 
> > 
> > Well I don't think I'll be comfortable on working on a same PR. It'll lead to discrepancies in future. This might make sense have made sense if we use the same fork.
> 
> Unsure of what you asked for. Are you referring to collaborator access to a fork? Yes I will have to provide you that on my fork.

Alright then. Provide me access to your fork. I hope it doesn't affect mine. Let us also discuss about a roadmap but on this issue #355.

**Comment by elit-altum** [comment]
@sanyamdogra fixed the failing builds. Separated other's commits for easy squashing at the end.

**Comment by sanyamdogra** [comment]
Hi @elit-altum, can you please fix the build? After that, I guess initial setup of the Storybook is done. We can get it reviewed by the team. I have added dummy stories that can be tackled one at a time.

**Comment by sanyamdogra** [comment]
@elit-altum I guess you'll have to change the directed PR to `development` rather than `master`.

**Comment by irmerk** [comment]
Screenshots:

---

Screen Shot 2020-03-17 at 1 24 39 PM

---

Screen Shot 2020-03-17 at 1 24 57 PM

**Comment by sanyamdogra** [comment]
> This looks like a good starting point! What are the next steps? With this in place, people will be able to go ahead and update the individual `.stories` files and add new `.stories` files for components that don't get have one?

Yes, we'll be able to write stories for every component that is used in cicero-ui.They can be checked in isolation and even tested. We'll still have to write stories for these components but that can be covered in individual PRs.

**Comment by DianaLease** [comment]
> > This looks like a good starting point! What are the next steps? With this in place, people will be able to go ahead and update the individual `.stories` files and add new `.stories` files for components that don't get have one?
> 
> Yes, we'll be able to write stories for every component that is used in cicero-ui.They can be checked in isolation and even tested. We'll still have to write stories for these components but that can be covered in individual PRs.

Sounds great to me!
It looks like some of your commits are missing the DCO signoff. You'll have to update your PR so that there no no commits without the signoff.

**Comment by sanyamdogra** [comment]
> > > This looks like a good starting point! What are the next steps? With this in place, people will be able to go ahead and update the individual `.stories` files and add new `.stories` files for components that don't get have one?
> > 
> > 
> > Yes, we'll be able to write stories for every component that is used in cicero-ui.They can be checked in isolation and even tested. We'll still have to write stories for these components but that can be covered in individual PRs.
> 
> Sounds great to me!
> It looks like some of your commits are missing the DCO signoff. You'll have to update your PR so that there no no commits without the signoff.

Me and @elit-altum tried hard to fix the build. The last commit has the DCO, somehow the travis is not building.

**Comment by sanyamdogra** [comment]
I don't know how it messed up the package-lock.json. Me and @elit-altum have tried to fix this but it's all scrambled. Closing this PR and making a new one.

**Comment by irmerk** [comment]
Closing for #353, @elit-altum make sure that PR isn't missing anything from this one.

**Pull request closed without merging**
