### PR TITLE
fix(TemplateLibrary): fixed highlighting of text on selection in SeachInput - I269

### LINKED ISSUE #269: No visual indication of clause template search bar highlighting
If I type text in the clause template search bar and then attempt to highlight the text, there is no visual indication that the text is highlighted, however I know the text is highlighted because if I press backspace, highlighted text will be deleted. I just can't see what's highlighted.

image

https://www.loom.com/share/75b31df8d96043d5911b844fdf2bb1ca

### PR DESCRIPTION
**Pull request by adrijshikhar**
Signed-off-by: adrijshikhar <adrijshikhar85@gmail.com>

# Issue #269 
fix #269 

### Changes
- Fix no highlight color of text in `SearchInput`
  - Change `:selection` pseudo-class `SearchInput` component on line 74

### Flags
- Snapshot
screen-cast-2020-02-22_12 35 36

### CODE REVIEW

**Comment by irmerk** [comment]
@Michael-Grover do the colors work, and is this a color we want the user to be able to customize?

**Comment by Michael-Grover** [comment]
the highlighting looks good to me @irmerk . I don't think we need to customize this color

**Comment by irmerk** [comment]
@adrijshikhar can you rebase with current master?

**Comment by adrijshikhar** [comment]
just a minute

**Pull request merged**
