### PR TITLE
feat(src): pass clause errors to plugin component - I282

### PR DESCRIPTION
**Pull request by irmerk**
# Issue #282
Use `clauseErrors` to determine if current clause is in error or not for UI colors

### Changes
- Update `README` and prop definitions
- Handle error or not color scheme with state and effect

### Flags
- `props.clauseErrors` in `src/ContractEditor/index.js` updates, but this does not propagate through the editor until the cursor is moved and Slate is forced to re-render

### Related Issues
- N/A

### CODE REVIEW

**Comment by irmerk** [comment]
Do you mean having [editor.props.clausePluginProps.onClauseUpdated](https://github.com/accordproject/cicero-ui/blob/master/src/plugins/ClausePlugin.js#L87) return a value which would be the parse result?

**Comment by DianaLease** [comment]
> Do you mean having [editor.props.clausePluginProps.onClauseUpdated](https://github.com/accordproject/cicero-ui/blob/master/src/plugins/ClausePlugin.js#L87) return a value which would be the parse result?

Yes (or parse error).

**Comment by irmerk** [comment]
@dselman I'd like your input when you're back on this, I paused after working with @DianaLease on this and we couldn't manage to get annotations or decorators to work.

**Comment by dselman** [comment]
I’m thinking perhaps we should check this behavior in Slate 0.50 before we waste too much time on this.

**Comment by elit-altum** [comment]
@irmerk I tried building your commit b2a909440875289185feb88801b31a285ebed1b2 which is the latest one (referred as b2a9094),  it outputs a log of errors on the console and the components fail to load resulting in a blank page, but the webpack build is successful. Could you help me work around this issue ?
Thank You.

image

I find most errors are coming from the ClauseComponent.js file after using the source maps.

**Comment by irmerk** [comment]
Unsure @elit-altum, are you working off the branch so you have the rest of the commits?

**Comment by elit-altum** [comment]
> 
> 
> Unsure @elit-altum, are you working off the branch so you have the rest of the commits?

Yes @irmerk I manually had cloned the commits which might have caused the error. I'll start working on the branch now.

**Pull request closed without merging**
